
# 📘 Học NumPy chi tiết (Tiếng Việt)

Trong notebook này, chúng ta sẽ học **NumPy** một cách chi tiết với nhiều ví dụ và bài tập thực hành.

---


## 1. Cài đặt và import thư viện

In [1]:

# Nếu chưa có numpy thì cài đặt (chỉ cần chạy 1 lần)
# !pip install numpy

import numpy as np
print("Phiên bản NumPy:", np.__version__)


Phiên bản NumPy: 2.3.3


## 2. Tạo mảng NumPy

In [2]:

# Tạo mảng từ list Python
arr1 = np.array([1, 2, 3, 4, 5])
print("Mảng arr1:", arr1)

# Tạo mảng 2 chiều
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Mảng 2D arr2:\n", arr2)

# zeros, ones, full
print("zeros:", np.zeros((2,3)))
print("ones:", np.ones((3,3)))
print("full:", np.full((2,2), 7))

# random
print("random (0-1):", np.random.rand(2,3))
print("random int (0-9):", np.random.randint(0,10,(2,3)))


Mảng arr1: [1 2 3 4 5]
Mảng 2D arr2:
 [[1 2 3]
 [4 5 6]]
zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full: [[7 7]
 [7 7]]
random (0-1): [[0.79858296 0.43285746 0.21201305]
 [0.10381422 0.66433791 0.84853334]]
random int (0-9): [[6 5 6]
 [4 3 0]]


## 3. Shape, Reshape, Indexing, Slicing

In [3]:

arr = np.arange(12)  # [0, 1, 2, ..., 11]
print("arr:", arr)
print("shape:", arr.shape)

# Reshape
arr2d = arr.reshape(3,4)
print("arr2d:\n", arr2d)

# Indexing
print("arr2d[0,0] =", arr2d[0,0])
print("arr2d[2,3] =", arr2d[2,3])

# Slicing
print("Hàng 1:", arr2d[0,:])
print("Cột 2:", arr2d[:,1])
print("Khối giữa:\n", arr2d[0:2, 1:3])


arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
shape: (12,)
arr2d:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr2d[0,0] = 0
arr2d[2,3] = 11
Hàng 1: [0 1 2 3]
Cột 2: [1 5 9]
Khối giữa:
 [[1 2]
 [5 6]]


## 4. Các phép toán trong NumPy

In [4]:

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[10,20,30],[40,50,60]])

print("Cộng:", x+y)
print("Trừ:", x-y)
print("Nhân từng phần:", x*y)
print("Chia:", x/y)

# Nhân ma trận (dot)
print("Nhân ma trận:", np.dot(x, y.T))

# Thống kê
print("Tổng:", np.sum(x))
print("Trung bình:", np.mean(x))
print("Max:", np.max(x))
print("Min:", np.min(x))


Cộng: [[11 22 33]
 [44 55 66]]
Trừ: [[ -9 -18 -27]
 [-36 -45 -54]]
Nhân từng phần: [[ 10  40  90]
 [160 250 360]]
Chia: [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
Nhân ma trận: [[140 320]
 [320 770]]
Tổng: 21
Trung bình: 3.5
Max: 6
Min: 1


## 5. Hàm Normalize dữ liệu

In [5]:

def normalize(arr):
    return (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

data = np.array([10, 20, 30, 40, 50])
print("Dữ liệu gốc:", data)
print("Sau khi normalize:", normalize(data))


Dữ liệu gốc: [10 20 30 40 50]
Sau khi normalize: [0.   0.25 0.5  0.75 1.  ]


## 6. Bài tập nhỏ


1. Tạo một ma trận 3x3 với số ngẫu nhiên từ 0 đến 9.
2. Tính tổng từng hàng và từng cột.
3. Viết hàm tính chuẩn hóa từng hàng trong ma trận.
4. Thực hiện nhân ma trận 3x2 và 2x3.
5. Lấy ra đường chéo chính của một ma trận vuông 4x4.
